spring.datasource:
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
spring.h2.console.enabled: true
spring.rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5673}
  username: ${RABBITMQ_USERNAME:camunda-demo}
  password: ${RABBITMQ_PASSWORD:guest}
camunda.bpm:
  history-level: full
  authorization:
    enabled: true
  filter:
    create: All tasks
  webapp.application-path:

security:
  oauth2:
    client:
      client-id: camunda-identity-service
      client-secret: ${KEYCLOAK_CLIENT_SECRET:cb10508b-320d-4826-b37e-713ba7df5611}
      accessTokenUri: http://localhost:9090/auth/realms/Camunda/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:9090/auth/realms/Camunda/protocol/openid-connect/auth
      scope: openid profile email
    resource:
      userInfoUri: http://localhost:9090/auth/realms/Camunda/protocol/openid-connect/userinfo

rest.security:
  enabled: true
  jwk-set-url: http://localhost:9090/auth/realms/camunda/protocol/openid-connect/certs
  required-audience: camunda-rest-api

server:
  port: 8080
logging:
  level:
#    org.camunda.bpm.engine.persistence: DEBUG
#    org.camunda.bpm.engine.cmd: DEBUG
#    org.camunda.bpm.engine.jobexecutor: DEBUG
    ROOT: info

# Externalized Keycloak configuration
keycloak:
  # Keycloak access for the Identity Provider plugin.
  url.plugin: ${KEYCLOAK_URL_PLUGIN:http://localhost:9090}
  url.auth: ${KEYCLOAK_URL_AUTH:http://localhost:9090}
  url.token: ${KEYCLOAK_URL_TOKEN:http://localhost:9090}

  # Keycloak Camunda Identity Client
  client.id: ${KEYCLOAK_CLIENT_ID:camunda-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET:cb10508b-320d-4826-b37e-713ba7df5611}

# Camunda Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url.plugin}/auth/realms/Camunda
  keycloakAdminUrl: ${keycloak.url.plugin}/auth/admin/realms/Camunda
  clientId: ${keycloak.client.id}
  clientSecret: ${keycloak.client.secret}
  useEmailAsCamundaUserId: true
  useUsernameAsCamundaUserId: false
  useGroupPathAsCamundaGroupId: true
  administratorGroupName: camunda-admin
